

name: Check CWT data from another workflow

on: 
  workflow_run:
    workflows: ["Check commits"]
    branches: [main, master]
    types:
      - completed
      

jobs:
  create:
    name: Push subfolder out to UPM branch
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: outputCommitsWithinTime
        path: exampleDownloadOfArtifactData

    - name: Read total commits from artifact JSON
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'exampleDownloadOfArtifactData/outputFromCommitsWithinTime.json'
        prop_path: "totalCommits"

    - name: Read hasNewCommitsWithinTime from artifact JSON
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'exampleDownloadOfArtifactData/outputFromCommitsWithinTime.json'
        prop_path: "hasNewCommitsWithinTime"

    - name: Read new commits from artifact JSON
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'exampleDownloadOfArtifactData/outputFromCommitsWithinTime.json'
        prop_path: "numberOfCommitsWithinTime"




    